version: '3.0'

services:
  frontend:
    build: 
      context: src/client
      dockerfile: Dockerfile
      args:
        server_url: http://localhost:8081
    ports:
      - '8080:80'
    depends_on:
      - api

  api:
    build:
      context: src/server
      dockerfile: ProSiRMQ.API/Dockerfile
    ports:
      - '8081:80'
    depends_on:
      - rabbit
      - database
    environment:
      - RABBITMQ_HOST=rabbit

      - DB_HOST=database
      - DB_PORT=5432
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - DB_DATABASE=postgres

  rabbit:
    image: rabbitmq:3.7-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    volumes:
      - ~/broker/data:/var/lib/rabbitmq
      - ~/broker/logs:/var/log/rabbitmq

  database:
    image: postgres:14-alpine
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USERNAME=postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - pgconf:/etc/postgresql
      - pglog:/var/log/postgresql
   
volumes:
  pgdata:
    driver: local
  pgconf:
    driver: local
  pglog:
    driver: local
    