version: '3.0'

services:
  frontend:
    build: 
      context: src/client
      dockerfile: Dockerfile
      args:
        server_url: http://localhost:8081
        file_server_url: http://localhost:8083
    ports:
      - '8080:80'
    depends_on:
      - message-api
      - file-api

  message-api:
    build:
      context: src/server
      dockerfile: ProSiRMQ.Message.API/Dockerfile
    ports:
      - '8081:80'
    depends_on:
      - rabbit
      - database
    environment:
      - RABBITMQ_HOST=rabbit

      - DB_HOST=database
      - DB_PORT=5432
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - DB_DATABASE=postgres

  message-listener:
    build:
      context: src/server
      dockerfile: ProSiRMQ.Message.Listener/Dockerfile
    ports:
      - '8082:80'
    depends_on:
      - rabbit
      - database
    environment:
      - RABBITMQ_HOST=rabbit

      - DB_HOST=database
      - DB_PORT=5432
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - DB_DATABASE=postgres

  file-api:
    build:
      context: src/server
      dockerfile: ProSiRMQ.File.API/Dockerfile
    ports:
      - '8083:80'
    environment:
      S3__HOST: http://minio:9000
      S3__USER: minio_user
      S3__PASSWORD: minio_password
      S3__BUCKET: "user-files"

      S3_SECRET: minio_user
      S3_PASSWORD: minio_password
      S3_BUCKET: "user-files"
      S3_HOST: http://minio:9000

  minio:
    image: minio/minio
    command: server --console-address ":9001" /data/
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minio_user
      MINIO_ROOT_PASSWORD: minio_password
    volumes:
      - minio-storage:/data
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9000/minio/health/live" ]
      interval: 30s
      timeout: 20s
      retries: 3

  rabbit:
    image: rabbitmq:3.7-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    volumes:
      - ~/broker/data:/var/lib/rabbitmq
      - ~/broker/logs:/var/log/rabbitmq

  database:
    image: postgres:14-alpine
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USERNAME=postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata_1:/var/lib/postgresql/data
      - pgconf_1:/etc/postgresql
      - pglog_1:/var/log/postgresql
   
volumes:
  pgdata_1:
    driver: local
  pgconf_1:
    driver: local
  pglog_1:
    driver: local
  minio-storage:
    driver: local